// <auto-generated />
namespace Antelope.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _11092014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11092014));
        
        string IMigrationMetadata.Id
        {
            get { return "201409110712450_11092014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
