//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PosteDeTravailType
    {
        public PosteDeTravailType()
        {
            this.PosteDeTravails = new HashSet<PosteDeTravail>();
        }
    
        public int PosteDeTravailTypeId { get; set; }
        public string Nom { get; set; }

        [JsonIgnore]
        public virtual ICollection<PosteDeTravail> PosteDeTravails { get; set; }
    }
}
